---
all:
  hosts:
  children:
    cisco:
      children:
        switches:
          children:
            cmo_switches:
              hosts:
                SMG30SW001:
                  hostname: SMG30SW001
            colo_switches:
              hosts:
                SMG10SW001:
                  hostname: SMG10SW001
            gannett_switches:
              hosts:
                SMG20SW001:
                  hostname: SMG20SW001
                SMG20SW002A:
                  hostname: SMG20SW002A
                SMG20SW002B:
                  hostname: SMG20SW002B
                SMG20SW003:
                  hostname: SMG20SW003
                SMG20WAN:
                  hostname: SMG20WAN
            cummings_switches:
              hosts: 
                SMG20SW004:
                  hostname: SMG20SW004
                SMG20SW005:
                  hostname: SMG20SW005
                SMG20SW006:
                  hostname: SMG20SW006
            emmc_switches:
              hosts:
                EMMCSW001:
                  hostname: EMMCSW001
                EMMCSW002:
                  hostname: EMMCSW002
            brunswick_switches:
              hosts:
                SMG70SW001:
                  hostname: SMG70SW001
            norway_switches:
              hosts:
                SMG90SW001:
                  hostname: SMG90SW001
            portland_switches:
              hosts:
                SMG40SW001:
                  hostname: SMG40SW001
                SMG40SW002:
                  hostname: SMG40SW002
                SMG40SW003:
                  hostname: SMG40SW003
                SMG40SW004:
                  hostname: SMG40SW004
            saco_switches:
              hosts: 
                SMG50SW001:
                  hostname: SMG50SW001
            windham_switches:
              hosts: 
                SMG60SW001:
                  hostname: SMG60SW001
                SMG60SW002:
                  hostname: SMG60SW002
          vars:
            type: switch
        routers:
          children:
            cmo_routers:
              hosts:
                SMG30RTR001:
                  hostname: SMG30RTR001
                SMG30RTR002:
                  hostname: SMG30RTR002
            colo_routers:
              hosts:
                SMG10NX001:
                  hostname: SMG10NX001
                  ansible_network_os: nxos
                SMG10NX002:
                  hostname: SMG10NX002
                  ansible_network_os: nxos
                SMG10RTR001:
                  hostname: SMG10RTR001
            cummings_routers:
              hosts:
                SMGCUmmingsRdSRST:
                  hostname: SMGCUmmingsRdSRST
            gannett_routers:
              hosts:
                SMG-Nexus-1:
                  hostname: SMG-Nexus-1
                  ansible_network_os: nxos
                SMG-Nexus-2:
                  hostname: SMG-Nexus-2
                  ansible_network_os: nxos
                SMG20RTR001:
                  hostname: SMG20RTR001
                SMG-Core-3850:
                  hostname: SMG-Core-3850
                Spectrum-Voice-GW:
                  hostname: Spectrum-Voice-GW
            brunswick_routers:
              hosts:
                SMG70RTR001:
                  hostname: SMG70RTR001
                SMG70RTR002:
                  hostname: SMG70RTR002
            portland_routers:
              hosts: 
                SMG40RTR001:
                  hostname: SMG40RTR001
                SMG40RTR002:
                  hostname: SMG40RTR002
            saco_routers:
              hosts:
                SMG50RTR001:
                  hostname: SMG50RTR001
                SMG50RTR002:
                  hostname: SMG50RTR002
            windham_routers:
              hosts: 
                SMG60RTR001:
                  hostname: SMG60RTR001
                SMG60RTR002:
                  hostname: SMG60RTR002
          vars:
            type: router
    fortinet:
      children:
        firewalls:
          children:
            colo_fw:
              hosts:
                SHCP10FW001:
                  hostname: SHCP10FW001
            emmc_fw:
              hosts:
                SHCP-EMMC-100F:
                  hostname: SHCP-EMMC-100F
            gannett_fw:
              hosts:
                SMG-FG500D-A-PRI:
                  hostname: SMG-FG500D-A-PRI        
            norway_fw:
              hosts: 
                SMG-MON-FG60D:
                  hostname: SMG-MON-FG60D
            portland_fw:
              hosts:
                SMG40FW001:
                  hostname: SMG60FW001
          vars:
            type: firewall
    cmo:
      children:
        cmo_switches:
        cmo_routers:
      vars:
        site: cmo
        site_code: 30
    colo: 
      children:
        colo_switches:
        colo_routers:
        colo_fw:
      vars:
        site: colo
        site_code: 10
    cummings:
      children:
        cummings_switches:
        cummings_routers:
      vars:
        site: cummings
        site_code: 20
    emmc: 
      children:
        emmc_switches:
        emmc_fw:
      vars:
        site: emmc
        site_code: 80
    gannett:
      children:
        gannett_switches:
        gannett_routers:
        gannett_fw:
      vars:
        site: gannett
        site_code: 20
    norway:
      children:
        norway_fw:
        norway_switches:
      vars:
        site: norway
        site_code: 90
    brunswick: 
      children:
        brunswick_switches:
        brunswick_routers:
      vars:
        site: brunswick
        site_code: 70
    portland: 
      children:
        portland_switches:
        portland_routers:
        portland_fw:
      vars: 
        site: portland
        site_code: 40
    saco: 
      children:
        saco_switches:
        saco_routers:
      vars:
        site: saco
        site_code: 50
    windham: 
      children:
        windham_switches:
        windham_routers:
      vars:
        site: windham
        site_code: 60



# ---
# all:
#   hosts:
#   children:
#     ios_devices:
#       children:
#         gannett_ios:
#           children:
#             switches:
#               hosts:
#                 SMGNorway:
#                 SMG20SW001:
#                 SMG20SW002A:
#                 SMG20SW002B:
#                 SMG20SW003:
#                 SMG20WAN:
#             routers:
#               hosts:
#                 SMG-Nexus-1:
#                 SMG-Nexus-2:
#                 SMG20RTR001:
#                 SMG-Core-3850:
#                 Spectrum-Voice-GW:
#         cummings_ios:
#           children:
#             switches:
#               hosts:
#                 SMG20SW004:
#         emmc_ios:
#           hosts:
#             EMMCSW001:
#             EMMCSW002:
#         brunswick_ios:
#           hosts:
#     fortinet_devices:
#       children:
#         gannett_forti:
#          hosts:
#           SMG-FG500D-A-PRI:        
#         norway_forti:
#           hosts: 
#             SMG-MON-FG60D:




# all:
#   hosts:
#   children:
#     gannett:
#     vars:
#       site: gannett
#       children:
#         ios_devices:
#           hosts:
#             SMGNorway:
#             SMG-Nexus-1:
#         fortinet_devices:
#           hosts:
#             SMG-MON-FG60D:
#     cummings:
#     vars:
#       site: cummings
#       children:
#         ios_devices:
#           hosts:
#             SMG20SW004:
#     vars:
#       site: cummings
#       norway:
#         hosts: 
#           SMG-MON-FG60D:
#       vars:
#         site: norway
    

