---
- name: send show command
  hosts: cisco
  gather_facts: false
  connection: network_cli
  vars:
    cmd: sh logg | i size

  tasks:
    - ios_command:
        commands: "{{ cmd }}"
      register: output

    - name: print output
      debug:
        var: output.stdout_lines[0][0]
