---
- name: set motd banner
  hosts: cisco
  connection: network_cli
  gather_facts: false
  vars:
    motd: |
      +                                                                 +
                                           ####                                
                                        ##########
                                    ################
                                  ##############
                                #############
                              ##########  
                              #########    ####
                              #########     ######
                                ######     ########
                                    ####    #########
                                          ###########
                                       ############
                                    #############
                                ###############
                                  ##########
                                    ####
        +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

        WARNING: This equipment is part of a private network.  It is for
        authorized use only. Users (authorized or unauthorized) have
        no explicit or implicit expectation of privacy.
        Any or all uses of this system and all files on this system may
        be intercepted, monitored, recorded, copied, audited, inspected,
        and disclosed to authorized site, corporate, and law enforcement
        personnel, as well as authorized officials of other agencies,
        both domestic and foreign. By using this system, the user
        consents to such interception, monitoring, recording, copying,
        auditing, inspection, and disclosure at the discretion of
        authorized site or corporate personnel.
        Unauthorized or improper use of this system may result in
        administrative disciplinary action and civil and criminal
        penalties. By continuing to use this system you indicate your
        awareness of and consent to these terms and conditions of use.

        LOG OFF IMMEDIATELY - if you do not agree to the conditions
        stated in this warning.

        ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    
  tasks:
    - name: remove ios banner
    - ios_config:
        lines:
          - no banner motd
      when: ansible_network_os == "ios"


    - name: set ios banner
      ios_banner: 
        banner: motd
        text: "{{ motd }}"
        state: present
      when: ansible_network_os == "ios"

      
    - ios_config:
        save_when: modified
      when: ansible_network_os =="ios"


    - name: remove nxos banner
      nxos_config:
        lines:
        - no banner motd
      when: ansible_network_os == "nxos"


    - name: set nxos banner
      nxos_banner: 
        banner: motd
        text: "{{ motd }}"
        state: present
      when: ansible_network_os == "nxos"


    - nxos_config:
        save_when: modified
      when: ansible_network_os == "nxos"


